### PR TITLE
More Features! SSL, PreAuthorisation and PartialCancellation And last_printout fix

### PR DESCRIPTION
**Pull request by kaisims**
I had to implement some features for a personal project and I wanted to share them!

Add support for connected devices via Socket to communicate via SSL Connection. Just add a flag to the url ( "socket://ip?ssl=true" )
Add support for Preauthorisations and PartialCancellation. Works very similar to normal Authorisation.

Fix for last_printout. Works again!

Add support to add a TLV to the Registration Commnand

### CODE REVIEW

**Comment by karolyi** [comment]
Thanks for your contribution!

I don't see tests but since you use these changes, I'll assume they're working. I'll merge them for now but please be prepared to touch your code again if/when someone comes up with any complaints.

**Comment by karolyi** [comment]
alright, so tests are already failing.

please correct your code to make the tests pass: https://travis-ci.org/github/karolyi/py3-ecrterm/builds/710709105

**Comment by kaisims** [comment]
I am new to open source development and contribution, so I dont have much experience! 
The tests in the build without my code merged fails aswell so I am not sure what causes it to fail and if my code is the reason https://travis-ci.org/github/karolyi/py3-ecrterm/builds/579393377
https://travis-ci.org/github/karolyi/py3-ecrterm/builds/710710575

**Comment by karolyi** [comment]
Your commits build upon another contributor's commit whom we never tested for. I'm way too busy now to untangle this mess, but if you look at the logs, it's flake8 (PEP8) errors, shouldn't be hard to search for them and correct them.

I might take the time for that later on. Do you use your changes in production without errors?

**Comment by karolyi** [comment]
@kaisims ping

**Comment by kaisims** [comment]
@karolyi Sorry for taking so long!
I fixed the flake8 erros in my latest commit.

Oh and I use my changes. But I wouldnt call it production as its only a prototype.

**Comment by karolyi** [comment]
@kaisims can you please issue a new pull request with the flake8 fixes please? I need to make sure that the tests work, and then I'll merge it.

**Pull request merged**
